In [1]:
import numpy as np

arr1 = np.array([1,2,3,4])

arr2 = np.array([5,6,7,8], dtype = float)
arr2.dtype

arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.shape(arr3)

(3, 3)

In [2]:
import numpy as np
import pandas as pd

# Мы можем преобразовать датафрейм или его часть, содержащую количественные показатели, 
# в объект ndarray с помошью функции values библиотеки Pandas.
df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [3]:
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values

array([ 5,  6,  7,  8,  9, 10])

In [4]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [7]:
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7

array([ 0,  7, 14])

In [10]:
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 10

array([[0, 3, 6],
       [5, 3, 2],
       [4, 0, 2]])

In [12]:
np.array([[8,13,18,4], 
          [25,3,18,28], 
          [14,15,18,24], 
          [1,2,3,4]]) 

# The main diagonal of a matrix consists of those elements that lie on the diagonal that runs from 
# top left to bottom right. 
# the main diagonal there is 8, 3, 18, 4

array([[ 8, 13, 18,  4],
       [25,  3, 18, 28],
       [14, 15, 18, 24],
       [ 1,  2,  3,  4]])

In [13]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.full((5,5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.array([[1,2,3,4,5], [5,1,2,3,4], [4,5,1,2,3], [3,4,5,1,2], [2,3,4,5,1]])

array([[1, 2, 3, 4, 5],
       [5, 1, 2, 3, 4],
       [4, 5, 1, 2, 3],
       [3, 4, 5, 1, 2],
       [2, 3, 4, 5, 1]])

In [19]:
np.random.randint(0, 4, (3, 3))

array([[2, 0, 2],
       [1, 2, 2],
       [1, 1, 1]])

In [20]:
np.random.randint(0, 5, (3, 3))

array([[0, 1, 1],
       [4, 3, 4],
       [3, 3, 0]])

In [21]:
np.random.randint(0, 6, (3, 3))

array([[5, 5, 1],
       [5, 3, 4],
       [5, 2, 3]])

In [22]:
np.random.randint(0, 5, 3)

array([4, 4, 3])

In [23]:
np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [24]:
np.ones((4, 4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.full((4, 4), 1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
np.array(range(9))

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [28]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

In [29]:
np.arange(1, 14, 2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [30]:
# Основные правила:

# ● индекс первого элемента массива равен 0;
# ● для обращения к элементу массива по индексу необходимо указать имя переменной, в которой хранится массив, и индекс в квадратных скобках;
# ● допускается использование отрицательных индексов;
# ● для обращения к нескольким идущим подряд элементам массива создаётся срез, в котором указывается индекс первого элемента среза и индекс элемента, следующего за последним, разделённые двоеточием;
# ● при создании среза возможно задание шага, в этом случае в срез будут включены не все элементы, а только отстоящие друг от друга на величину шага.
# Рассмотрим примеры использования индексов при работе с одномерным массивом. Попробуйте самостоятельно выполнить код:

In [31]:
my_array = np.array([x for x in range(10)])
my_array[5]

5

In [32]:
my_array[-1]

9

In [33]:
my_array[3:6]

array([3, 4, 5])

In [34]:
my_array[1:8:3] # 1 to 8, step 3

array([1, 4, 7])

In [35]:
# При работе с двумерными массивами для обращения к элементу мы указываем два индекса, 
# соответствующие [номеру строки] и [номеру столбца]. Каждый индекс можно указывать в отдельных квадратных 
# скобках или внутри одной пары скобок через запятую.

In [36]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48]])

In [37]:
my_array[1,1] # row 1 -> means 10,11,12,13; column 1 -> means 2,11,46

11

In [38]:
my_array[1] # row 1 -> means 10,11,12,13

array([10, 11, 12, 13])

In [39]:
my_array[2,1] # row 2 -> means 45,46,47,48; column 1 -> means 2,11,46

46

In [40]:
my_array[2] # row 2 -> means 45,46,47,48

array([45, 46, 47, 48])

In [41]:
# 
# Потренируемся извлекать из двумерного массива отдельные элементы и их срезы и производить над ними 
# математические действия.

In [42]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

In [43]:
# 6.3.1
# Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:


In [44]:
sum = 0
for i in range(5):
    sum += big_secret[i][-1]
print(sum)

3154.332495807108


In [45]:
# 6.3.2
# Выделите из каждой строки массива big_secret первые 5 элементов. 
# Чему равна сумма элементов главной диагонали получившейся матрицы? 
# Округлите ответ до двух цифр после запятой:

In [62]:
bs2 = big_secret[0:5,0:5] # slicing -> 0 to 5 for rows; 0 to 5 for columns
print(bs2)
sum = 0
for i in range(0,5):
    sum += bs2[i][i]
sum

[[14.         10.          6.         56.         40.        ]
 [31.6227766  31.65438358 31.68595904 31.71750305 31.74901573]
 [ 0.          1.          4.          9.         16.        ]
 [31.6227766  31.65438358 31.68595904 31.71750305 31.74901573]
 [14.         10.          6.         56.         40.        ]]


121.37188663699624

In [47]:
# 6.3.3
# Выделите из каждой строки массива big_secret последние 5 элементов. 
# Чему равно произведение элементов главной диагонали получившейся матрицы? 
# Введите полученный результат без изменений и округлений.

In [74]:
bs2 = big_secret[0:5,-5:] # slicing -> 0 to 5 for rows; 0 to 5 for columns
print(bs2)
sum = 1
for i in range(0,5):
    sum = sum * bs2[i][i]
sum

[[ 460.          276.          686.          490.          294.        ]
 [  33.04542328   33.07567082   33.10589071   33.13608305   33.1662479 ]
 [2116.         2209.         2304.         2401.         2500.        ]
 [  33.04542328   33.07567082   33.10589071   33.13608305   33.1662479 ]
 [ 460.          276.          686.          490.          294.        ]]


341505315559.2347

In [ ]:
# Упражнения
# Проверим знания! Продолжим работать с массивом big_secret. 
# Замените на 1 все элементы, у которых оба индекса нечётные, и на -1 все элементы, 
# у которых оба индекса чётные.

In [78]:
rows, cols = big_secret.shape
print(f"rows = '{rows}' and cols = '{cols}'")

rows = '5' and cols = '51'


In [80]:
for i in range(rows):
    for y in range(cols):
        if (i % 2 == 0) & (y % 2 == 0):
            big_secret[i][y] = -1
        else:
            big_secret[i][y] = 1

big_secret 

array([[-1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,
         1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1.,
        -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,
         1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,
         1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1.,
        -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,
         1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., 

In [ ]:
# 6.3.4 
# Выделите из каждой строки обновлённого массива big_secret первые 5 элементов. 
# Чему равна сумма элементов главной диагонали получившейся матрицы? 
# Введите полученный ответ без изменений и округлений.


In [81]:
bs2 = big_secret[0:5,0:5] # slicing -> 0 to 5 for rows; 0 to 5 for columns
print(bs2)
sum = 0
for i in range(0,5):
    sum += bs2[i][i]
sum

[[-1.  1. -1.  1. -1.]
 [ 1.  1.  1.  1.  1.]
 [-1.  1. -1.  1. -1.]
 [ 1.  1.  1.  1.  1.]
 [-1.  1. -1.  1. -1.]]


-1.0

In [ ]:
# 6.3.5
# Выделите из каждой строки обновлённого массива big_secret последние 5 элементов. 
# Чему равно произведение элементов главной диагонали получившейся матрицы? 
# Введите полученный результат без изменений и округлений.


In [82]:
bs2 = big_secret[0:5,-5:] # slicing -> 0 to 5 for rows; 0 to 5 for columns
print(bs2)
sum = 1
for i in range(0,5):
    sum = sum * bs2[i][i]
sum

[[-1.  1. -1.  1. -1.]
 [ 1.  1.  1.  1.  1.]
 [-1.  1. -1.  1. -1.]
 [ 1.  1.  1.  1.  1.]
 [-1.  1. -1.  1. -1.]]


-1.0

In [ ]:
# 6.4

In [83]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(
    result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [84]:
# Функция Описание
# Example using NumPy: np.isnan(имя_массива):
# ● abs                     -> Абсолютное значение целых, вещественных или комплексных элементов массива
# ● sqrt                    -> Квадратный корень каждого элемента массива
# ● exp                     -> Экспонента (ex) каждого элемента массива
# ● log, log10, log2, log1p -> Натуральный (по основанию е), десятичный, двоичный логарифм и функция log(1+x) соответственно
# ● modf                    -> Дробные и целые части массива в виде отдельных массивов
# ● isnan                   -> Массив логических (булевых) значений, показывающий, какие из элементов исходного массива  являются NaN (не числами)
# ● cos, sin, tan           -> Обычные тригонометрические функции
# ● arccos, arcsin, arctan  -> Обратные тригонометрические функции

In [90]:
# use T or transpose if you want to switch rows on columns
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(my_array)
my_array.T

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [88]:
# use reshape if you want to change 1D array to 2D array
my_array = np.random.randint(0, 10, 20)
print(my_array)
my_array.reshape((4,5))

[2 1 2 8 3 1 8 9 0 0 2 6 9 4 1 6 6 2 3 0]


array([[2, 1, 2, 8, 3],
       [1, 8, 9, 0, 0],
       [2, 6, 9, 4, 1],
       [6, 6, 2, 3, 0]])

In [89]:
# use flatten if you want to change 2D array to 1D array
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
print(my_array)
my_array.flatten()

[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]


array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [93]:
# masks
my_array = np.random.randint(0, 10, (3,4))
print(my_array)
my_array<5

[[0 0 6 6]
 [8 4 5 8]
 [9 7 6 2]]


array([[ True,  True, False, False],
       [False,  True, False, False],
       [False, False, False,  True]])

In [94]:
my_array[my_array<5]

array([0, 0, 4, 2])

In [95]:
# Маска нужна для выбора только определенных строк или столбцов из всего массива и скрытия остальных. 
# Маска в Python задаётся при помощи булевых 0 и 1, где 0 скрывает столбец или строку, а 1 оставляет ее на виду.
# Выведем первый и третрий столбец массива:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[0, 6],
       [8, 5],
       [9, 6]])

In [ ]:
# В двумерных массивах можно выполнять сортировку элементов строк и столбцов:

# Сортировка выполняется с помощью функции sort, в качестве параметров функция получает сам массив, 
# а также номер оси (0 (для столбцов) или 1 (для строк)) , элементы которой необходимо отсортировать. 

# Как можно отсортировать элементы строк и столбцов?

In [97]:
my_array = np.random.randint(0, 10, (4, 6))
print(my_array)

[[1 9 6 8 5 0]
 [2 3 3 9 8 1]
 [6 4 6 5 9 0]
 [7 8 2 9 5 5]]


In [98]:
np.sort(my_array, axis=1) # for rows

array([[0, 1, 5, 6, 8, 9],
       [1, 2, 3, 3, 8, 9],
       [0, 4, 5, 6, 6, 9],
       [2, 5, 5, 7, 8, 9]])

In [99]:
np.sort(my_array, axis=0) # for columns

array([[1, 3, 2, 5, 5, 0],
       [2, 4, 3, 8, 5, 0],
       [6, 8, 6, 9, 8, 1],
       [7, 9, 6, 9, 9, 5]])

In [101]:
# Exercises
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T
print(great_secret)

[[ 0.          4.64158883 66.66666667]
 [ 1.          4.65700951 40.        ]
 [ 1.41421356  4.67232873 67.33333333]
 [ 1.73205081  4.68754815 40.4       ]
 [ 2.          4.70266938 68.        ]
 [ 2.23606798  4.71769398 40.8       ]
 [ 2.44948974  4.73262349 68.66666667]
 [ 2.64575131  4.7474594  41.2       ]
 [ 2.82842712  4.76220316 69.33333333]
 [ 3.          4.77685618 41.6       ]
 [ 3.16227766  4.79141986 70.        ]
 [ 3.31662479  4.80589553 42.        ]
 [ 3.46410162  4.82028453 70.66666667]
 [ 3.60555128  4.83458813 42.4       ]
 [ 3.74165739  4.84880759 71.33333333]
 [ 3.87298335  4.86294413 42.8       ]
 [ 4.          4.87699896 72.        ]
 [ 4.12310563  4.89097325 43.2       ]
 [ 4.24264069  4.90486813 72.66666667]
 [ 4.35889894  4.91868473 43.6       ]
 [ 4.47213595  4.93242415 73.33333333]
 [ 4.58257569  4.94608744 44.        ]
 [ 4.69041576  4.95967566 74.        ]
 [ 4.79583152  4.97318983 44.4       ]
 [ 4.89897949  4.98663095 74.66666667]
 [ 5.          5.        

In [102]:
# 6.4.1
# Сколько столбцов содержит массив great_secret?
rows, cols = great_secret.shape
print(f"rows = '{rows}' and cols = '{cols}'")

rows = '100' and cols = '3'


In [105]:
# 6.4.2
# Чему равна сумма косинусов элементов первой строки массива great_secret? 
# Ответ округлите до двух знаков после запятой.
cos = np.cos(great_secret[0])
sum = np.sum(cos)
print(sum)

0.16006721889793019


In [106]:
# 6.4.3
# Чему равна сумма элементов массива great_secret, значение которых больше 50?
great_secret > 50
over_50 = great_secret[great_secret > 50]
print(over_50)

[66.66666667 67.33333333 68.         68.66666667 69.33333333 70.
 70.66666667 71.33333333 72.         72.66666667 73.33333333 74.
 74.66666667 75.33333333 76.         76.66666667 77.33333333 78.
 78.66666667 79.33333333 80.         80.66666667 81.33333333 82.
 82.66666667 83.33333333 84.         50.4        84.66666667 50.8
 85.33333333 51.2        86.         51.6        86.66666667 52.
 87.33333333 52.4        88.         52.8        88.66666667 53.2
 89.33333333 53.6        90.         54.         90.66666667 54.4
 91.33333333 54.8        92.         55.2        92.66666667 55.6
 93.33333333 56.         94.         56.4        94.66666667 56.8
 95.33333333 57.2        96.         57.6        96.66666667 58.
 97.33333333 58.4        98.         58.8        98.66666667 59.2
 99.33333333 59.6       ]


In [107]:
sum = np.sum(over_50)
print(sum)

5470.0


In [108]:
# 6.4.4
# Переведите массив great_secret в одномерную форму. 
# Какое значение в получившемся массиве имеет элемент с индексом 150? 
# Скопируйте ответ из Jupyter Notebook без изменений.
great_secret.flatten()[150]

7.0710678118654755

In [ ]:
# 6.4.5
# Отсортируйте значения столбцов массива great_secret по возрастанию. 
# Чему равна сумма элементов последней строки отсортированного массива? 
# Ответ округлите до двух цифр после запятой.

In [121]:
np.sort(great_secret, axis=0)[-1].sum() # for columns

115.12148016521353

In [120]:
great_secret[-1].sum()

75.3881468318802

In [115]:
rows, cols = great_secret.shape

print(f"rows = '{rows}' and cols = '{cols}'")

rows = '100' and cols = '3'


In [117]:
print(great_secret[99])

[ 9.94987437  5.83827246 59.6       ]
