In [1]:
import numpy as np
import pandas as pd
import math 

# 1.2.1

# На рынке новостроек появилось предложение от застройщика "Гарантия" — 
# двухкомнатная квартира общей площадью 59.50 кв.м, жилой площадью 31.40 кв.м на 19-м этаже 22-х этажного дома. 
# В доме 2 подъезда. Цена за квадратный метр квартиры у этого застройщика составляет 60550 рублей.
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])
# вычислим долю жилой площади в квартире
share_living_space = apartment[1]/apartment[0]
# Избавимся от старых признаков
apartment = np.delete(apartment, [0, 1])
# добавим в конец нашего массива новый признак share_living_space
apartment = np.append(apartment, share_living_space)

# Введите значение получившегося нового признака share_living_space. 
# Используйте код и ссылки на документацию из описания квартиры.
print(round(share_living_space, 2))

0.53


In [2]:
# 1.2.2
# Укажите размерность конечного массива apartment после преобразования 
# (ввода новой переменной и удаления старых).
len(apartment)

5

In [3]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
print(t[5])
print(min(t))

28
12


In [4]:
# 1.3.3

a1 = np.array([120, 150, 90])
a2 = np.array([130, 130, 130])
a3 = np.array([2, 3, 2.5])
a4 = a3 * 72
print(a4)
print(a1 + a2 + a4)

[144. 216. 180.]
[394. 496. 400.]


In [5]:
# 1.4.1
x = np.array([4,5])
y = np.array([2,1])
u = np.array([1,0])
2 * x + (-3)* y + 5 * u

array([7, 7])

In [6]:
# 1.4.2
# Юный предприниматель Вовочка мастерит ракеты на водном топливе и продает их. 
# За 4 недели он смастерил 3, 4, 5 и 9 ракет, а продал 1, 5, 3 и 6 ракет соответственно.
# На изготовление одной ракеты он тратит 200 рублей, а продаёт их по 400 рублей за штуку.
# Найдите вектор прибыли Вовочки за эти 4 недели.
rockets = np.array([3,4,5,9])
rockets_expenses = 200 * rockets
print(rockets_expenses)
sold = np.array([1,5,3,6])
profit = 400 * sold
print(profit)
net_profit = profit - rockets_expenses
print(net_profit)

[ 600  800 1000 1800]
[ 400 2000 1200 2400]
[-200 1200  200  600]


In [7]:
# 1.5.2
v1 = np.array([4,5,-1])
v2 = np.array([2,0,1])
np.dot(v1, v2)

7

In [8]:
# 1.5.3
# Длина вектора вычисляется как квадратный корень из скалярного произведения вектора с самим собой. 
# Для нас это это просто корень из суммы квадратов координат, как в теореме 
# Пифагора — для случая с размерностью вектора равной двум (геометрически это длина отрезка).

v = np.array([4,6,1])
v2 = v * v
print(v2)
print(math.sqrt(v2[0] + v2[1] + v2[2]))

[16 36  1]
7.280109889280518


In [9]:
# Скалярное произведение двух векторов, необходимо перемножить их координаты с одинаковыми номерами 
# и сложить то, что получится.
# Векторы a и b называются ортогональными, если их скалярное произведение равно нулю.
print(np.dot(np.array([4,2,-1]), np.array([2,0,1])))
print(np.dot(np.array([4,5,1]), np.array([0,0,0])))
print(np.dot(np.array([4,-1]), np.array([-1,4])))
print(np.dot(np.array([4,-1]), np.array([1,4])))

7
0
-8
0


In [10]:
# 1.7
df = pd.DataFrame({             '1.Rent'          :[65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area'          :[50, 52, 80,  33, 33, 44, 80,  65, 65], 
                                '3.Rooms'         :[3,  2,  1,   1,  1,  2,  4,   3,  2],
                                '4.Floor'         :[5,  12, 10,  3,  6,  13, 8,   21, 5], 
                                '5.Demo two weeks':[8,  4,  5,   10, 20, 12, 5,   1,  10], 
                                '6.Liv.Area'      :[37, 40, 65,  20, 16, 35, 60,  50, 40]})
print(df.iloc[2, 3].tolist())
print(len(df.iloc[:,2].tolist()))
# 1.7.5
aarea = df.iloc[:,1]
larea = df.iloc[:,5]
print((aarea - larea).tolist())
# 1.7.6
print(((df.iloc[:,0] * 1000 * 4 / 10 / 1000).astype(int)).tolist())
print('1.7.7')
# Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса,
# в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, 
# в восьмой — 8 минут и в девятой — 20 минут. Найдите продолжительность просмотров в минутах во 
# всех квартирах за 2 недели.
time = [10, 20, 30, 15, 5, 40, 20, 8, 20] 
df['7. Time'] = time


tt = 0
for i in range(0, len(df.iloc[:,2].tolist())):
    tt += df.iloc[i][4] * df.iloc[i][6]

print(tt)

10
9
[13, 12, 15, 13, 17, 9, 20, 15, 25]
[26, 28, 48, 14, 16, 20, 40, 36, 34]
1.7.7
1348


In [11]:
# 1.7.8
u=np.array([3, 0, 1, 1, 1])
v=np.array([0, 1, 0, 2,-2])
w=np.array([1,-4,-1, 0,-2])
np.dot(u, v)
np.dot(v, w)

z = 2 * v + (-3) * w
z

array([-3, 14,  3,  4,  2])

In [12]:
# 1.7.9
np.dot(u, z)

0

In [13]:
# 1.7.10
from numpy import linalg as LNG 

lu = LNG.norm(u)
lv = LNG.norm(v)
lw = LNG.norm(w)
print(round(lu,3))
print(round(lv,3))
print(round(lw,3))

print(round((u / lu)[3],3))
print(round((v / lv)[4],3))
print(round((w / lw)[0],3))

3.464
3.0
4.69
0.289
-0.667
0.213


In [14]:
# 1.10
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

# 1.10.1
# Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тещи в первый, второй и третий столбцы.
# В ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую (без пробела).
inc = np.array([[100, 150, 90], 
                [220, 200, 80], 
                [140, 130, 100]])
# 1.10.2
# Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тещи в первый, второй и третий столбцы.
# В ответ запишите диагональные элементы (по побочной диагонали) этой матрицы через запятую (без пробела).
cons = np.array([[50, 100, 100], 
                 [50,  80,  20], 
                 [60, 140, 140]])
# 1.10.3
# Доходы представлены до уплаты налогов. Налоговая ставка - 13%. 
# Вычислите матрицу доходов семьи Ивановых после уплаты налогов.
# Используйте матрицу Inc из предыдущего вопроса, где расходы расположены по столбцам. 
# В ответ запишите элементы из 1 строки этой матрицы через запятую (без пробела).
inc_net = 0.87 * inc
inc_net

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [15]:
# 1.10.4
# Вычислите матрицу P, которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами и расходами)
# В ответ запишите элементы из 3 строки этой матрицы через запятую (без пробела).
p = inc_net - cons
p

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [16]:
# 1.11.2
a = np.array([[1, -1, 2, 4, 0], [8,2,0,5,3], [0,1,2,1,2]])
b = np.array([[1, 0, 1, 0], [0, 0, 2, -1], [1, 0, 1, 1], [0, 1, 1, 1], [1, 1, 0, -1]])
np.dot(a, b)

array([[ 3,  4,  5,  7],
       [11,  8, 17,  0],
       [ 4,  3,  5,  0]])

In [17]:
# 1.14.2
a = np.array([[1, 1], [2, -1], [1, 2]])
at = a.T
at
np.dot(a, at)

array([[2, 1, 3],
       [1, 5, 0],
       [3, 0, 5]])

In [18]:
# 1.15.1
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

# Найдите произведение матрицы A и вектора X в том порядке, в котором их можно умножить.
# Координаты вектора введите через запятую (без пробела):

np.dot(A,x)

array([26, 30])

In [19]:
# 1.15.2
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
# Найдите произведение матриц A и B в том порядке, в котором их можно умножить.
# В ответ запишите элемент из 1 строки и 4 столбца
np.dot(B, A)

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [21]:
# 1.15.3
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

# Найдите матрицу Грама системы векторов 
# Введите все элементы этой матрицы через запятую (без пробела), перечисляя построчно:

g = np.array([[1,2,1,0,4], [2,1,-1,1,0], [-1,1,-1,0,0]])
g @ g.T

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

In [25]:
# 1.15.4
count_df = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                         'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                         'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                         'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                         'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
}, index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
price_df = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                         'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                         'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                         'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                         'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
}, index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

# Найдите вектор выручки Бориса.
# Введите координаты вектора через запятую (без пробела).
count_df.head(10)

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [33]:
print(count_df.iloc[1,:].tolist())
print(price_df.iloc[1,:].tolist())

[2, 21, 3, 25, 6]
[1.8, 2.5, 1.0, 1.0, 1.0]


In [38]:
boris_count = np.array(count_df.iloc[1,:].tolist())
boris_price = np.array(price_df.iloc[1,:].tolist())
print(boris_count)
print(boris_price)
boris_count * boris_price

[ 2 21  3 25  6]
[1.8 2.5 1.  1.  1. ]


array([ 3.6, 52.5,  3. , 25. ,  6. ])

In [46]:
# 1.15.5
# Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят определенную комиссию салону.
# Вектор комиссий com = [0.2, 0.2, 0.3, 0.1, 0.1]
# Введите координаты вектора через запятую (без пробела).
count_np = np.array(count_df)
price_np = np.array(price_df)
count = count_np * price_np
print(count)
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
com_profit = count @ com
com_profit

[[20.   7.5 12.  12.  10. ]
 [ 3.6 52.5  3.  25.   6. ]
 [24.  24.   0.  15.   8. ]
 [ 7.2  9.6 50.4 11.2 10. ]
 [15.  87.5 54.  25.  27. ]
 [50.  15.   6.  34.  30. ]
 [24.2  1.   6.  12.5 34. ]
 [31.5  0.  77.5 31.  56. ]]


array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [47]:
# 1.15.6
# Найдите вектор прибыли стилистов.
# Введите координаты вектора через запятую (без пробела).
style = np.array([0.8, 0.8, 0.7, 0.9, 0.9])
style_profit = count @ style
style_profit

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [56]:
# 1.16.1
f1 = np.matrix("1,2; 2,5")
f1

matrix([[1, 2],
        [2, 5]])

In [57]:
np.linalg.inv(f1)

matrix([[ 5., -2.],
        [-2.,  1.]])

In [59]:
# 1.20.1
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
# Найдите обратную матрицу к матрице А.
# В ответ запишите элемент из 2 строки и 1 столбца, округлив его до трёх знаков после запятой.
A

array([[ 8,  6, 11],
       [ 7,  5,  9],
       [ 6, 10,  6]])

In [61]:
A1_inv = np.linalg.inv(A)
A1_inv

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [66]:
# 1.20.2
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])
v = np.array([[9, 10, 7, 7, 9], [2, 0, 5, 1, 4], [4, 0, 0, 4, 1], [3, -4, 3, -1, -4]])
# Найдите ранг системы векторов v1, v2, v3, v4.
np.linalg.matrix_rank(v)

4

In [68]:
# 1.20.4
print('Матрица Грама:\n',v@v.T)

Матрица Грама:
 [[360  96  73 -35]
 [ 96  46  16   4]
 [ 73  16  33   4]
 [-35   4   4  51]]


In [70]:
# 1.20.5
# Найдите определитель матрицы Грама системы v1, v2, v3, v4.
round(np.linalg.det(v@v.T))

3716648.0

In [72]:
# 1.20.7
# Найдите обратную матрицу к матрице Грама системы v1, v2, v3, v4.
np.linalg.inv(v@v.T)

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])